- name: install software
  become: yes
  hosts: all
  vars:
   ansible_user: ec2-user
   ansible_password: DevOps321
  tasks:
  - name: install runtime software
    ansible.builtin.dnf:
     name: nginx
     state: latest